Name:           ros-indigo-tra1-moveit-config
Version:        1.0.9
Release:        0%{?dist}
Summary:        ROS tra1_moveit_config package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-joint-state-publisher
Requires:       ros-indigo-joy
Requires:       ros-indigo-moveit-fake-controller-manager
Requires:       ros-indigo-moveit-kinematics
Requires:       ros-indigo-moveit-planners-ompl
Requires:       ros-indigo-moveit-ros-move-group
Requires:       ros-indigo-moveit-ros-visualization
Requires:       ros-indigo-moveit-ros-warehouse
Requires:       ros-indigo-moveit-simple-controller-manager
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-rviz
Requires:       ros-indigo-tra1-description
Requires:       ros-indigo-warehouse-ros
Requires:       ros-indigo-xacro
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roslaunch
BuildRequires:  ros-indigo-rostest

%description
An automatically generated package with all the configuration and launch files
for using the tra1 with the MoveIt! Motion Planning Framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Mar 02 2018 Ryosuke Tajima <ryosuke.tajima@opensource-robotics.tokyo.jp> - 1.0.9-0
- Autogenerated by Bloom

* Mon Nov 06 2017 Ryosuke Tajima <ryosuke.tajima@opensource-robotics.tokyo.jp> - 1.0.7-1
- Autogenerated by Bloom

* Mon Nov 06 2017 Ryosuke Tajima <ryosuke.tajima@opensource-robotics.tokyo.jp> - 1.0.7-0
- Autogenerated by Bloom

* Tue Sep 12 2017 Ryosuke Tajima <ryosuke.tajima@opensource-robotics.tokyo.jp> - 1.0.6-0
- Autogenerated by Bloom

* Tue Sep 12 2017 Ryosuke Tajima <ryosuke.tajima@opensource-robotics.tokyo.jp> - 1.0.5-0
- Autogenerated by Bloom

* Mon Sep 11 2017 Ryosuke Tajima <ryosuke.tajima@opensource-robotics.tokyo.jp> - 1.0.4-0
- Autogenerated by Bloom

